### ISSUE TITLE
Floordiv for SizeValue

### ISSUE THREAD

**Issue by vieting** [rwth-i6/pytorch-to-returnn#105]
When `stride > 1` in the convolution in `test_negative_sampling`, the `SizeValue` for the `torch_shape` in `_ConvNd._get_output_shape_from_returnn` is computed using floordiv. This currently fails. 

I'll make this change to the test in a PR and post log and stack trace here.

**Comment by albertz** [comment]
You mean, it should be ceildiv instead, right?

**Comment by vieting** [comment]
No, I think using floordiv is correct. It just currently results in `ValueError: unknown op kind 'floordiv_right'` in `Dim.complete_dyn_size`. I'll post the full error once the tests in #106 finish.

**Comment by vieting** [comment]
See tests in #106 [here](https://github.com/rwth-i6/pytorch-to-returnn/runs/5090649076?check_suite_focus=true)

Log

<details>

```
>>> Running with standard reference imports...

>>> Running with wrapped imports, wrapping original PyTorch...
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch._jit_internal._copy_to_script_wrapper(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch._jit_internal._overload_method(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.empty(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.nn.init.kaiming_uniform_(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.nn.init._calculate_fan_in_and_fan_out(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.nn.init.uniform_(...)
*** torch module call pytorch_to_returnn.import_wrapper._torch_traced.torch.nn.modules.conv.Conv1d(...)(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.nn.functional.conv1d(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.arange(...)
*** func call pytorch_to_returnn.import_wrapper._torch_traced.torch.cat(...)
>>>> Module naming hierarchy:
.tmp_root: (hidden, empty)
Conv1d: <ModuleEntry Conv1d(7, 7, kernel_size=(2,), stride=(3,))> -> ...
WrappedTorchFunction: <ModuleEntry <WrappedObject '_.WrappedTorchFunction(...)' type <class 'pytorch_to_returnn.import_wrapper.torch_wrappers.function.WrappedTorchFunction'>>> -> ...
>>>> Root module calls:
>>>> Modules with params:
>>>> Looks good!

>>> Running with wrapped Torch import, wrapping replacement for PyTorch...
RETURNN input: Data{'data', [B,T|'time:data'[B],F|F'feature:data'(7)]}
*** root/'Transpose' layer dict: {'class': 'copy', 'from': 'data'}
*** root/'Transpose' CopyLayer output: <TensorEntry name:? tensor:(B(3),F'feature:data'(7)(7),'time:data'[B](15)) returnn_data:'Transpose_output' [B,T|'time:data'[B],F|F'feature:data'(7)] axes {0:0,2:1,1:2}>
*** root/'Conv1d' layer dict: {'class': 'conv', 'from': 'Transpose', 'activation': None, 'with_bias': True, 'n_out': 7, 'filter_size': (2,), 'padding': 'valid', 'in_spatial_dims': ['T'], 'strides': (3,)}
*** root/'Conv1d' ConvLayer output: <TensorEntry name:? tensor:(B(3),'static_dim'(7)(7),'((time:data+-2)//3)+1'[?](5)) returnn_data:'Conv1d_output' [B,T|'Conv1d:conv:s0'[B],F|F'Conv1d:channel'(7)] axes {0:0,2:1,1:2}>
*** root/'Conv1d' ConvLayer importing params ['weight', 'bias'] ...
*** root/'Conv1d' ConvLayer check RETURNN inputs/outputs given Torch inputs/outputs ...
**** validate: add network input tensor <TensorEntry name:? tensor:(B(3),'time:data'[B](15),F'feature:data'(7)(7)) returnn_data:'data' [B,T|'time:data'[B],F|F'feature:data'(7)] axes id>
**** validate: add call <CallEntry 'Conv1d' <ModuleEntry <Conv1d>> (depth 0)> input tensor <TensorEntry name:? tensor:(B(3),F'feature:data'(7)(7),'time:data'[B](15)) returnn_data:'Transpose_output' [B,T|'time:data'[B],F|F'feature:data'(7)] axes {0:0,2:1,1:2}>
**** validate: add call <CallEntry 'Conv1d' <ModuleEntry <Conv1d>> (depth 0)> output tensor <TensorEntry name:? tensor:(B(3),'static_dim'(7)(7),'((time:data+-2)//3)+1'[?](5)) returnn_data:'Conv1d_output' [B,T|'Conv1d:conv:s0'[B],F|F'Conv1d:channel'(7)] axes {0:0,2:1,1:2}>
*** root/'Transpose_1' layer dict: {'class': 'copy', 'from': 'Conv1d'}
*** root/'Transpose_1' CopyLayer output: <TensorEntry name:? tensor:(B(3),'((time:data+-2)//3)+1'[?](5),'static_dim'(7)(7)) returnn_data:'Transpose_1_output' [B,T|'Conv1d:conv:s0'[B],F|F'Conv1d:channel'(7)] axes id>
*** root/'Range_Length' layer dict: {'class': 'length', 'axis': 'T', 'from': 'data'}
*** root/'Range_Length' LengthLayer output: <TensorEntry name:? tensor:(B(3),) returnn_data:'time:data:dyn_size' [B] axes id>
*** root/'Range_Reduce' layer dict: {'class': 'reduce', 'mode': 'max', 'axes': ['B'], 'from': 'Range_Length'}
*** root/'Range_Reduce' ReduceLayer output: <TensorEntry name:? tensor:() returnn_data:'Range_Reduce_output' [] axes id>
*** root/'Range_sub_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'Range_sub_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Range_sub_unnamed_const_const' [] axes id>
*** root/'Range_sub' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Range_Reduce', 'Range_sub_unnamed_const']}
*** root/'Range_sub' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Range_sub_output' [] axes id>
*** root/'Range_sub_unnamed_const_1' layer dict: {'class': 'constant', 'value': 1}
*** root/'Range_sub_unnamed_const_1' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Range_sub_unnamed_const_1_const' [] axes id>
*** root/'Range_sub_1' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Range_sub', 'Range_sub_unnamed_const_1']}
*** root/'Range_sub_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Range_sub_1_output' [] axes id>
*** root/'Range_floordiv_unnamed_const' layer dict: {'class': 'constant', 'value': 3}
*** root/'Range_floordiv_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Range_floordiv_unnamed_const_const' [] axes id>
*** root/'Range_floordiv' layer dict: {'class': 'combine', 'kind': 'floordiv', 'out_shape': set(), 'from': ['Range_sub_1', 'Range_floordiv_unnamed_const']}
*** root/'Range_floordiv' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Range_floordiv_output' [] axes id>
*** root/'Range_add_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'Range_add_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Range_add_unnamed_const_const' [] axes id>
*** root/'Range_add' layer dict: {'class': 'combine', 'kind': 'add', 'out_shape': set(), 'from': ['Range_floordiv', 'Range_add_unnamed_const']}
*** root/'Range_add' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Range_add_output' [] axes id>
*** root/'Range' layer dict: {'class': 'range_from_length', 'from': 'Range_add'}
*** root/'Range' RangeFromLengthLayer output: <TensorEntry name:? tensor:('((time:data+-2)//3)+1'[?](5),) returnn_data:'Range_output' [T|'Range_input_len'[]] axes id>
*** root/'Unflatten_Length' layer dict: {'class': 'length', 'axis': 'T', 'from': 'data'}
*** root/'Unflatten_Length' LengthLayer output: <TensorEntry name:? tensor:(B(3),) returnn_data:'time:data:dyn_size' [B] axes id>
*** root/'Unflatten_Reduce' layer dict: {'class': 'reduce', 'mode': 'max', 'axes': ['B'], 'from': 'Unflatten_Length'}
*** root/'Unflatten_Reduce' ReduceLayer output: <TensorEntry name:? tensor:() returnn_data:'Unflatten_Reduce_output' [] axes id>
*** root/'Unflatten_sub_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'Unflatten_sub_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Unflatten_sub_unnamed_const_const' [] axes id>
*** root/'Unflatten_sub' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Unflatten_Reduce', 'Unflatten_sub_unnamed_const']}
*** root/'Unflatten_sub' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Unflatten_sub_output' [] axes id>
*** root/'Unflatten_sub_unnamed_const_1' layer dict: {'class': 'constant', 'value': 1}
*** root/'Unflatten_sub_unnamed_const_1' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Unflatten_sub_unnamed_const_1_const' [] axes id>
*** root/'Unflatten_sub_1' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Unflatten_sub', 'Unflatten_sub_unnamed_const_1']}
*** root/'Unflatten_sub_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Unflatten_sub_1_output' [] axes id>
*** root/'Unflatten_floordiv_unnamed_const' layer dict: {'class': 'constant', 'value': 3}
*** root/'Unflatten_floordiv_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Unflatten_floordiv_unnamed_const_const' [] axes id>
*** root/'Unflatten_floordiv' layer dict: {'class': 'combine', 'kind': 'floordiv', 'out_shape': set(), 'from': ['Unflatten_sub_1', 'Unflatten_floordiv_unnamed_const']}
*** root/'Unflatten_floordiv' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Unflatten_floordiv_output' [] axes id>
*** root/'Unflatten_add_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'Unflatten_add_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'Unflatten_add_unnamed_const_const' [] axes id>
*** root/'Unflatten_add' layer dict: {'class': 'combine', 'kind': 'add', 'out_shape': set(), 'from': ['Unflatten_floordiv', 'Unflatten_add_unnamed_const']}
*** root/'Unflatten_add' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Unflatten_add_output' [] axes id>
*** root/'Unflatten' layer dict: {'class': 'split_dims', 'from': 'Range', 'axis': 'T', 'dims': [-1, 1]}
*** root/'Unflatten' SplitDimsLayer output: <TensorEntry name:? tensor:('((time:data+-2)//3)+1'[?](5),'static_dim'(1)(1)) returnn_data:'Unflatten_output' [T|'Range_input_len'[],F|'Unflatten_split_dims1'(1)] axes id>
*** root/'Tile' layer dict: {'class': 'tile', 'multiples': {'T': 1, 'F': 10}, 'from': 'Unflatten'}
*** root/'Tile' TileLayer output: <TensorEntry name:? tensor:('((time:data+-2)//3)+1'[?](5),'static_dim'(10)(10)) returnn_data:'Tile_output' [T|'Range_input_len'[],F|'10*Unflatten_split_dims1'(10)] axes id>
*** root/'Flatten' layer dict: {'class': 'merge_dims', 'from': 'Tile', 'axes': ['T', 'F'], 'keep_order': True}
*** root/'Flatten' MergeDimsLayer output: <TensorEntry name:? tensor:('(((time:data+-2)//3)+1)*static_dim'[?](50),) returnn_data:'Flatten_output' [F|'Range_input_len*10*Unflatten_split_dims1'[]] axes id>
*** root/'randint_Length' layer dict: {'class': 'length', 'axis': 'T', 'from': 'data'}
*** root/'randint_Length' LengthLayer output: <TensorEntry name:? tensor:(B(3),) returnn_data:'time:data:dyn_size' [B] axes id>
*** root/'Length_randint_Reduce' layer dict: {'class': 'reduce', 'mode': 'max', 'axes': ['B'], 'from': 'randint_Length'}
*** root/'Length_randint_Reduce' ReduceLayer output: <TensorEntry name:? tensor:() returnn_data:'Length_randint_Reduce_output' [] axes id>
*** root/'randint_sub_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_sub_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_sub_unnamed_const_const' [] axes id>
*** root/'Reduce_randint_sub' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Length_randint_Reduce', 'randint_sub_unnamed_const']}
*** root/'Reduce_randint_sub' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Reduce_randint_sub_output' [] axes id>
*** root/'randint_sub_unnamed_const_1' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_sub_unnamed_const_1' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_sub_unnamed_const_1_const' [] axes id>
*** root/'sub_randint_sub' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Reduce_randint_sub', 'randint_sub_unnamed_const_1']}
*** root/'sub_randint_sub' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'sub_randint_sub_output' [] axes id>
*** root/'randint_floordiv_unnamed_const' layer dict: {'class': 'constant', 'value': 3}
*** root/'randint_floordiv_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_floordiv_unnamed_const_const' [] axes id>
*** root/'sub_randint_floordiv' layer dict: {'class': 'combine', 'kind': 'floordiv', 'out_shape': set(), 'from': ['sub_randint_sub', 'randint_floordiv_unnamed_const']}
*** root/'sub_randint_floordiv' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'sub_randint_floordiv_output' [] axes id>
*** root/'randint_add_unnamed_const' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_add_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_add_unnamed_const_const' [] axes id>
*** root/'floordiv_randint_add' layer dict: {'class': 'combine', 'kind': 'add', 'out_shape': set(), 'from': ['sub_randint_floordiv', 'randint_add_unnamed_const']}
*** root/'floordiv_randint_add' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'floordiv_randint_add_output' [] axes id>
*** root/'randint_sub_unnamed_const_2' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_sub_unnamed_const_2' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_sub_unnamed_const_2_const' [] axes id>
*** root/'add_randint_sub' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['floordiv_randint_add', 'randint_sub_unnamed_const_2']}
*** root/'add_randint_sub' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'add_randint_sub_output' [] axes id>
*** root/'sub_randint_Length' layer dict: {'class': 'length', 'axis': 'B', 'from': 'data'}
*** root/'sub_randint_Length' LengthLayer output: <TensorEntry name:? tensor:() returnn_data:'sub_randint_Length_batch_dim' [] axes id>
*** root/'Length_randint_Length' layer dict: {'class': 'length', 'axis': 'T', 'from': 'data'}
*** root/'Length_randint_Length' LengthLayer output: <TensorEntry name:? tensor:(B(3),) returnn_data:'time:data:dyn_size' [B] axes id>
*** root/'Length_randint_Reduce_1' layer dict: {'class': 'reduce', 'mode': 'max', 'axes': ['B'], 'from': 'Length_randint_Length'}
*** root/'Length_randint_Reduce_1' ReduceLayer output: <TensorEntry name:? tensor:() returnn_data:'Length_randint_Reduce_1_output' [] axes id>
*** root/'randint_sub_unnamed_const_3' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_sub_unnamed_const_3' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_sub_unnamed_const_3_const' [] axes id>
*** root/'Reduce_randint_sub_1' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Length_randint_Reduce_1', 'randint_sub_unnamed_const_3']}
*** root/'Reduce_randint_sub_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'Reduce_randint_sub_1_output' [] axes id>
*** root/'randint_sub_unnamed_const_4' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_sub_unnamed_const_4' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_sub_unnamed_const_4_const' [] axes id>
*** root/'sub_randint_sub_1' layer dict: {'class': 'combine', 'kind': 'sub', 'out_shape': set(), 'from': ['Reduce_randint_sub_1', 'randint_sub_unnamed_const_4']}
*** root/'sub_randint_sub_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'sub_randint_sub_1_output' [] axes id>
*** root/'randint_floordiv_unnamed_const_1' layer dict: {'class': 'constant', 'value': 3}
*** root/'randint_floordiv_unnamed_const_1' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_floordiv_unnamed_const_1_const' [] axes id>
*** root/'sub_randint_floordiv_1' layer dict: {'class': 'combine', 'kind': 'floordiv', 'out_shape': set(), 'from': ['sub_randint_sub_1', 'randint_floordiv_unnamed_const_1']}
*** root/'sub_randint_floordiv_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'sub_randint_floordiv_1_output' [] axes id>
*** root/'randint_add_unnamed_const_1' layer dict: {'class': 'constant', 'value': 1}
*** root/'randint_add_unnamed_const_1' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_add_unnamed_const_1_const' [] axes id>
*** root/'floordiv_randint_add_1' layer dict: {'class': 'combine', 'kind': 'add', 'out_shape': set(), 'from': ['sub_randint_floordiv_1', 'randint_add_unnamed_const_1']}
*** root/'floordiv_randint_add_1' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'floordiv_randint_add_1_output' [] axes id>
*** root/'randint_mul_unnamed_const' layer dict: {'class': 'constant', 'value': 10}
*** root/'randint_mul_unnamed_const' ConstantLayer output: <TensorEntry name:'value' tensor:() returnn_data:'randint_mul_unnamed_const_const' [] axes id>
*** root/'add_randint_mul' layer dict: {'class': 'combine', 'kind': 'mul', 'out_shape': set(), 'from': ['randint_mul_unnamed_const', 'floordiv_randint_add_1']}
*** root/'add_randint_mul' CombineLayer output: <TensorEntry name:? tensor:() returnn_data:'add_randint_mul_output' [] axes id>
*** root/'mul_randint_Cast' layer dict: {'class': 'cast', 'from': 'add_randint_sub', 'dtype': 'int64'}
*** root/'mul_randint_Cast' CastLayer output: <TensorEntry name:? tensor:() returnn_data:'mul_randint_Cast_output' [] axes id>
*** root/'mul_randint' layer dict: {'class': 'rand_int', 'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}), 'maxval': 'mul_randint_Cast', 'minval': 0, 'dtype': 'int64', 'from': ['data']}
Exception creating layer root/'mul_randint' of class RandIntLayer with opts:
{'_name': 'mul_randint',
 '_network': <TFNetwork 'root' train=False>,
 'dtype': 'int64',
 'maxval': <CastLayer 'mul_randint_Cast' out_type=Data{[], dtype='int64'}>,
 'minval': 0,
 'name': 'mul_randint',
 'network': <TFNetwork 'root' train=False>,
 'output': Data{'mul_randint_output', [B,T|'(10*((time:data+-2)//3))+10'[?]], dtype='int64'},
 'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}),
 'sources': [<SourceLayer 'data' out_type=Data{[B,T|'time:data'[B],F|F'feature:data'(7)]}>]}
```

</details>

Traceback

<details>

```
 Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/nose/case.py", line 198, in TestBase.runTest
    line: self.test(*self.arg)
    locals:
      self = <local> test_layers.test_negative_sampling
      self.test = <local> <function test_negative_sampling at 0x7f7c18fcd3a0>
      self.arg = <local> ()
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/tests/test_layers.py", line 76, in test_negative_sampling
    line: verify_torch_and_convert_to_returnn(model_func, inputs=x, inputs_data_kwargs={
            "shape": (None, n_feat), "batch_dim_axis": 0, "time_dim_axis": 1, "feature_dim_axis": 2})
    locals:
      verify_torch_and_convert_to_returnn = <global> <function verify_torch_and_convert_to_returnn at 0x7f7c18fc7d30>
      model_func = <local> <function test_negative_sampling.<locals>.model_func at 0x7f7c18fb39d0>
      inputs = <not found>
      x = <local> array([[[ 0.49671414, -0.1382643 ,  0.64768857,  1.5230298 ,
                           -0.23415338, -0.23413695,  1.5792128 ],
                          [ 0.7674347 , -0.46947438,  0.54256004, -0.46341768,
                           -0.46572974,  0.24196227, -1.9132802 ],
                          [-1.7249179 , -0.5622875 , -1.0128311 ,  0.31424734,
                           -0.9080..., len = 3, _[0]: {len = 15, _[0]: {len = 7}}
      inputs_data_kwargs = <not found>
      n_feat = <local> 7
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 403, in verify_torch_and_convert_to_returnn
    line: converter.run()
    locals:
      converter = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7f7c18d87df0>
      converter.run = <local> <bound method Converter.run of <pytorch_to_returnn.converter.converter.Converter object at 0x7f7c18d87df0>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 139, in Converter.run
    line: self._run_torch_returnn_drop_in()
    locals:
      self = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7f7c18d87df0>
      self._run_torch_returnn_drop_in = <local> <bound method Converter._run_torch_returnn_drop_in of <pytorch_to_returnn.converter.converter.Converter object at 0x7f7c18d87df0>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/converter/converter.py", line 254, in Converter._run_torch_returnn_drop_in
    line: out_returnn = self._model_func(wrapped_import_torch_returnn, in_returnn)
    locals:
      out_returnn = <not found>
      self = <local> <pytorch_to_returnn.converter.converter.Converter object at 0x7f7c18d87df0>
      self._model_func = <local> <function test_negative_sampling.<locals>.model_func at 0x7f7c18fb39d0>
      wrapped_import_torch_returnn = <global> <function wrapped_import_torch_returnn at 0x7f7c18fc7ca0>
      in_returnn = <local> <Tensor name:? tensor:(B(3),'time:data'[B](15),F'feature:data'(7)(7)) returnn_data:'data' [B,T|'time:data'[B],F|F'feature:data'(7)] axes id>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/tests/test_layers.py", line 64, in test_negative_sampling.<locals>.model_func
    line: neg_idxs = torch.randint(low=0, high=tsz - 1, size=(bsz, n_negatives * tsz))  # (B,T*N)
    locals:
      neg_idxs = <not found>
      torch = <local> <module 'pytorch_to_returnn.torch' from '/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/__init__.py'>
      torch.randint = <local> <function randint at 0x7f7c38e3a040>
      low = <not found>
      high = <not found>
      tsz = <local> '((time:data+-2)//3)+1'[?](5)
      size = <not found>
      bsz = <local> B(3)
      n_negatives = <local> 10
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/nn/functional.py", line 107, in randint
    line: return mod(low, high, size, dtype)
    locals:
      mod = <local> <RandInt>
      low = <local> 0
      high = <local> '(time:data+-2)//3'[?](4)
      size = <local> (B(3), '(10*((time:data+-2)//3))+10'[?](50))
      dtype = <local> None
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/torch/nn/modules/module.py", line 439, in Module.__call__
    line: res = call_entry.apply_call()
    locals:
      res = <not found>
      call_entry = <local> <CallEntry 'mul_randint' <ModuleEntry <RandInt>> (depth 0)>
      call_entry.apply_call = <local> <bound method CallEntry.apply_call of <CallEntry 'mul_randint' <ModuleEntry <RandInt>> (depth 0)>>
  File "/home/runner/work/pytorch-to-returnn/pytorch-to-returnn/pytorch_to_returnn/naming/call.py", line 139, in CallEntry.apply_call
    line: layer = returnn_net.construct_layer(net_dict={layer_name: layer_dict}, name=layer_name)
    locals:
      layer = <not found>
      returnn_net = <local> <TFNetwork 'root' train=False>
      returnn_net.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork 'root' train=False>>
      net_dict = <not found>
      layer_name = <local> 'mul_randint', len = 11
      layer_dict = <local> {'class': 'rand_int', 'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}), 'maxval': 'mul_randint_Cast', 'minval': 0, 'dtype': 'int64', 'from': ['data']}, len = 6
      name = <not found>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 946, in TFNetwork.construct_layer
    line: return add_layer(name=name_with_prefix, layer_class=layer_class, **layer_desc)
    locals:
      add_layer = <local> <bound method TFNetwork.add_layer of <TFNetwork 'root' train=False>>
      name = <local> 'mul_randint', len = 11
      name_with_prefix = <local> 'mul_randint', len = 11
      layer_class = <local> <class 'returnn.tf.layers.basic.RandIntLayer'>
      layer_desc = <local> {'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}), 'maxval': <CastLayer 'mul_randint_Cast' out_type=Data{[], dtype='int64'}>, 'minval': 0, 'dtype': 'int64', '_network': <TFNetwork 'root' train=False>, '_name': 'mul_randint', 'sources': [<SourceLayer 'data' out_type=Data{[B,T|'time:data'[?..., len = 7
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 1101, in TFNetwork.add_layer
    line: layer = self._create_layer(name=name, layer_class=layer_class, **layer_desc)
    locals:
      layer = <not found>
      self = <local> <TFNetwork 'root' train=False>
      self._create_layer = <local> <bound method TFNetwork._create_layer of <TFNetwork 'root' train=False>>
      name = <local> 'mul_randint', len = 11
      layer_class = <local> <class 'returnn.tf.layers.basic.RandIntLayer'>
      layer_desc = <local> {'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}), 'maxval': <CastLayer 'mul_randint_Cast' out_type=Data{[], dtype='int64'}>, 'minval': 0, 'dtype': 'int64', '_network': <TFNetwork 'root' train=False>, '_name': 'mul_randint', 'sources': [<SourceLayer 'data' out_type=Data{[B,T|'time:data'[?..., len = 7
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/network.py", line 1016, in TFNetwork._create_layer
    line: layer = layer_class(**layer_desc)
    locals:
      layer = <not found>
      layer_class = <local> <class 'returnn.tf.layers.basic.RandIntLayer'>
      layer_desc = <local> {'shape': (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]}), 'maxval': <CastLayer 'mul_randint_Cast' out_type=Data{[], dtype='int64'}>, 'minval': 0, 'dtype': 'int64', '_network': <TFNetwork 'root' train=False>, '_name': 'mul_randint', 'sources': [<SourceLayer 'data' out_type=Data{[B,T|'time:data'[?..., len = 10
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/layers/basic.py", line 2547, in RandIntLayer.__init__
    line: shape_ = [
            d.get_for_batch_ctx(batch, self.network.control_flow_ctx).get_dim_value()
            for d in self.output.dim_tags]
    locals:
      shape_ = <not found>
      d = <not found>
      d.get_for_batch_ctx = <not found>
      batch = <local> BatchInfo{B}
      self = <local> <RandIntLayer 'mul_randint' out_type=Data{[B,T|'(10*((time:data+-2)//3))+10'[?]], dtype='int64'}>
      self.network = <local> <TFNetwork 'root' train=False>
      self.network.control_flow_ctx = <local> None
      get_dim_value = <not found>
      self.output = <local> Data{'mul_randint_output', [B,T|'(10*((time:data+-2)//3))+10'[?]], dtype='int64'}
      self.output.dim_tags = <local> (Dim{B}, Dim{'(10*((time:data+-2)//3))+10'[?]})
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/layers/basic.py", line 2548, in <listcomp>
    line: d.get_for_batch_ctx(batch, self.network.control_flow_ctx).get_dim_value()
    locals:
      d = <local> Dim{'(10*((time:data+-2)//3))+10'[?]}
      d.get_for_batch_ctx = <local> <bound method Dim.get_for_batch_ctx of Dim{'(10*((time:data+-2)//3))+10'[?]}>
      batch = <local> BatchInfo{B}
      self = <local> <RandIntLayer 'mul_randint' out_type=Data{[B,T|'(10*((time:data+-2)//3))+10'[?]], dtype='int64'}>
      self.network = <local> <TFNetwork 'root' train=False>
      self.network.control_flow_ctx = <local> None
      get_dim_value = <not found>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/util/data.py", line 952, in Dim.get_dim_value
    line: self.complete_dyn_size()
    locals:
      self = <local> Dim{'(10*((time:data+-2)//3))+10'[?]}
      self.complete_dyn_size = <local> <bound method Dim.complete_dyn_size of Dim{'(10*((time:data+-2)//3))+10'[?]}>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/util/data.py", line 599, in Dim.complete_dyn_size
    line: x.complete_dyn_size()
    locals:
      x = <local> Dim{'10*((time:data+-2)//3)'[?]}
      x.complete_dyn_size = <local> <bound method Dim.complete_dyn_size of Dim{'10*((time:data+-2)//3)'[?]}>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/util/data.py", line 599, in Dim.complete_dyn_size
    line: x.complete_dyn_size()
    locals:
      x = <local> Dim{'(time:data+-2)//3'[?]}
      x.complete_dyn_size = <local> <bound method Dim.complete_dyn_size of Dim{'(time:data+-2)//3'[?]}>
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/util/data.py", line 596, in Dim.complete_dyn_size
    line: y.placeholder = _bin_op(y.placeholder, x.dimension)
    locals:
      y = <local> Data{'(time:data+-2)//3:seq-length', [B], dtype='int32'}
      y.placeholder = <local> <tf.Tensor 'mul_randint/add:0' shape=(?,) dtype=int32>
      _bin_op = <local> <function Dim.complete_dyn_size.<locals>._bin_op at 0x7f7c18c2b160>
      x = <local> Dim{'unnamed_spatial_dim_3'(3)}
      x.dimension = <local> 3
  File "/home/runner/.local/lib/python3.8/site-packages/returnn/tf/util/data.py", line 581, in Dim.complete_dyn_size.<locals>._bin_op
    line: raise ValueError("unknown op kind %r" % op.kind)
    locals:
      ValueError = <builtin> <class 'ValueError'>
      op = <local> <Dim.Op 'floordiv_right' [Dim{'time:data+-2'[?]}, Dim{'unnamed_spatial_dim_3'(3)}]>
      op.kind = <local> 'floordiv_right', len = 14
ValueError: unknown op kind 'floordiv_right'
```

</details>

**Comment by albertz** [comment]
> No, I think using floordiv is correct. It just currently results in `ValueError: unknown op kind 'floordiv_right'` in `Dim.complete_dyn_size`. I'll post the full error once the tests in #106 finish.

I pushed sth on RETURNN side which might fix this.

**Comment by vieting** [comment]
> I pushed sth on RETURNN side which might fix this.

Yes, it does. Locally, the test works for me now. Thanks!

**Comment by vieting** [comment]
The check passes now, see [here](https://github.com/rwth-i6/pytorch-to-returnn/runs/5091326854?check_suite_focus=true).
